kind: pipeline
type: docker
name: dev

steps:
- name: echo
  image: alpine
  commands:
  - echo hello
- name: build-dev
  image: alpine
  commands:
  - echo dev
  when:
    branch:
    - dev
- name: build-stg
  image: alpine
  commands:
  - echo stg
  when:
    branch:
    - stg
