kind: pipeline
type: docker
name: dev

steps:
- name: echo
  image: alpine
  commands:
  - echo hello
  - echo dev
- name: echo2
  image: alpine
  commands:
  - echo hello
  - echo neodev

trigger:
  branch:
  - dev

---
kind: pipeline
type: docker
name: stg

steps:
- name: echo
  image: alpine
  commands:
  - echo hello
  - echo stg

trigger:
  branch:
  - stg
